# -*- coding: utf-8 -*-
"""Copy of POS_Tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ALbqBAlmGSktGTbB5XakRas7Pl_YKcr
"""

import nltk
nltk.download('all')
import re
text="The/DT planet/NN Jupiter/NNP and/CC its/PPS moons/NNS are/VBP in/IN effect/NN a/DT minisolar/JJ system/?? ,/, and/CC Jupiter/NNP itself/PRP is/VBZ often/RB called/VBN a/DT star/?? that/IN never/RB caught/??? fire/NN ./."
#text2="People/NNS continue/VBP to/TO inquire/VB the/DT reason/?? for/IN the/DT race/NN for/IN outer/JJ space/??"
re_text2=re.sub('/(\S{2,3})', ' ', text)
word_tokens = nltk.word_tokenize(re_text2)
tag_token=nltk.pos_tag(word_tokens)
nouns = [word+"/"+pos for (word, pos) in nltk.pos_tag(word_tokens) ]
tagged=" ".join(map(str,nouns))
print(tagged)